Blog.Web/Models/ViewModels/HomeViewModel.cs
using Blog.Web.Models.Domain;

namespace Blog.Web.Models.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<BlogPost> BlogPosts { get; set; }

        public IEnumerable<Tag> Tags { get; set; }
    }
}

Blog.Web/Controllers/BlogsController.cs
using Blog.Web.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace Blog.Web.Controllers
{
    public class BlogsController : Controller
    {
        private readonly IBlogPostRepository blogPostRepository;

        public BlogsController(IBlogPostRepository blogPostRepository)
        {
            this.blogPostRepository = blogPostRepository;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string urlHandle)
        {
            var blogPost = await blogPostRepository.GetByUrlHandleAsync(urlHandle);

            return View(blogPost);
        }
    }
}

Blog.Web/Controllers/HomeController.cs
using Blog.Web.Models;
using Blog.Web.Models.ViewModels;
using Blog.Web.Repositories;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Blog.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IBlogPostRepository blogPostRepository;
        private readonly ITagRepository tagRepository;

        public HomeController(
            ILogger<HomeController> logger,
            IBlogPostRepository blogPostRepository,
            ITagRepository tagRepository
            )
        {
            _logger = logger;
            this.blogPostRepository = blogPostRepository;
            this.tagRepository = tagRepository;
        }

        public async Task<IActionResult> Index()
        {
            // Getting all blogs
            var blogPosts = await blogPostRepository.GetAllAsync();

            // Getting all tags
            var tags = await tagRepository.GetAllAsync();

            var homeModel = new HomeViewModel
            {
                BlogPosts = blogPosts,
                Tags = tags
            };

            return View(homeModel);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Blog.Web/Views/Home/Index.cshtml
@model Blog.Web.Models.ViewModels.HomeViewModel;

@{
    ViewData["Title"] = "Home Page";
}

<div class="container col-xxl-8 px-4 py-5">
    <div class="row align-items-center g-5 py-5">
        <div class="col-12 col-lg-6">
            <h1 class="display-5 fw-bold lh-1 mb-3">
                Blog - The Dev Blog
            </h1>
            <p class="lead">
                Blog is the home to coding blogs covering a vast range of topics like HTML,
                Javascript, ASP.NET, Golang, etc.
                Want to read the latest dev articles?
                Join the blog app and get weekly blogs in your email.
            </p>
        </div>
            
        <div class="col-12 col-lg-6">
            <img src="https://images.pexels.com/photos/3584923/pexels-photo-3584923.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
                alt="Blog - Dev blogs"
                class="d-block mx-lg-auto img-fluid" 
                width="350" 
            />
        </div>
    </div>
</div>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-6 d-flex mb-3">
            @if (Model != null && Model.Tags.Any())
            {
                foreach (var tags in Model.Tags)
                {
                    <span class="badge bg-dark me-1">
                        @tags.Name
                    </span>
                }
            }
        </div>
    </div>
</div>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-6">
            @if (Model != null && Model.BlogPosts.Any())
            {
                foreach (var blogPost in Model.BlogPosts)
                {
                    <div class="mb-5 bg-light box-shadow p-5">
                        <img src="@blogPost.FeaturedImageUrl" 
                            alt="@blogPost.Heading"
                            class="mb-2 d-block img-fluid"
                            />

                        <h2 class="mb-4">@blogPost.Heading</h2>
                        <p class="mb-4">
                            Author: @blogPost.Author
                            <br/>
                            Published Date: @blogPost.PublishedDate.ToShortDateString()
                        </p>

                        <p class="mb-4">
                            @foreach (var tag in blogPost.Tags)
                            {
                                <span class="badge bg-secondary me-1">@tag.Name</span>
                            }
                        </p>

                        <p class="mb-5">
                            @blogPost.ShortDescription
                        </p>

                        <a class="btn btn-dark"
                            asp-area=""
                            asp-controller="Blogs"
                            asp-action="Index"
                            asp-route-urlHandle="@blogPost.UrlHandle"
                            >Read More
                        </a>
                    </div>
                }
            }
        </div>
    </div>
</div>